config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get '/', to: 'dashboard#index'
    resources :courses do
      resources :lessons
    end
  end

  namespace :student do
    get 'dashboard', to: 'dashboard#index'
    get '/', to: 'dashboard#index'
    resources :lessons do
      resources :exams, except: [:index]
    end
    resources :exams, only: [:index]
  end

  root 'home#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
    @course_count = Course.count
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < StudentController
  def index
    @lesson_count = Lesson.count
  end
end

app/controllers/student/exams_controller.rb
class Student::ExamsController < StudentController
  before_action :set_lesson, only: %i[new create show]
  before_action :set_exam, only: %i[show]

  def index
    @exams = current_user.exams
  end

  def new
    @exam = @lesson.exams.new
    @exam.exam_answers.build
  end

  def create
    @exam = @lesson.exams.new
    @exam.user = current_user
    @exam.save
    if @exam.create_exam_answers(params[:exam][:exam_answers])
      redirect_to student_lesson_exam_path(@lesson, @exam),
                  success: 'Exam has been finished!'
    else
      redirect_to new_student_lesson_exam_path,
                  error: 'Exam could not be finished!'
    end
  end

  def show
    @score = @exam.score
  end

  private

  def exam_params
    params.require(:exam).permit(
      :user_id, :lesson_id,
      exam_answers_attributes: ExamAnswer.attribute_names
                                         .map(&:to_sym)
                                         .push(:_destroy)
      )
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end
end

app/controllers/student/lessons_controller.rb
class Student::LessonsController < StudentController
  def index
    @lessons = Lesson.all.includes(:course)
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :check_student_access

  private

  def check_student_access
    if user_signed_in?
      unless current_user.student?
        redirect_to root_path
      end
    else
      redirect_to root_path, error: force_login_message
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/student/dashboard_helper.rb
module Student::DashboardHelper
end

app/helpers/student/exams_helper.rb
module Student::ExamsHelper
end

app/helpers/student/lessons_helper.rb
module Student::LessonsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/dashboard/index.html.slim
.row
  .col-md-4
    .card
      .card-header
        h5 Lessons
      .card-body
        .card-title
          .row
            .col-md-8
              h6 Total Lessons
            .col-md-4.text-end
              h6 = @lesson_count
        .text-end
          = link_to student_lessons_path, class: "btn btn-sm btn-success"
            i.fa.fa-eye aria-hidden="true"
            span.ms-1 View
  .col-md-4
    .card
      .card-header
        h5 Exams
      .card-body
        .card-title
          .row
            .col-md-8
              h6 Your exams
            .col-md-4.text-end
              h6 = current_user.exams.count
        .text-end
          = link_to student_exams_path, class: "btn btn-sm btn-success"
            i.fa.fa-eye aria-hidden="true"
            span.ms-1 View
  .col-md-4